# Generated by Django 5.2.6 on 2025-10-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pendencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pendency",
            options={"verbose_name": "Pendência", "verbose_name_plural": "Pendências"},
        ),
        migrations.AddField(
            model_name="pendency",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
