# Generated by Django 5.2.6 on 2025-10-28 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
            },
        ),
    ]
