# Generated by Django 5.2.6 on 2025-10-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_alter_appointment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ativo", "Ativo"),
                    ("finalizado", "Finalizado"),
                    ("cancelado", "Cancelado"),
                ],
                null=True,
            ),
        ),
    ]
