# Generated by Django 5.2.6 on 2025-11-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="type",
            field=models.CharField(
                choices=[
                    ("Consulta", "Consulta"),
                    ("Retorno", "Retorno"),
                    ("Avaliação", "Avaliação"),
                    ("Outro", "Outro"),
                ],
                max_length=20,
            ),
        ),
    ]
