# Generated by Django 5.2.6 on 2026-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_alter_appointment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="referral_professionals",
            field=models.TextField(
                blank=True,
                help_text="Códigos dos profissionais separados por vírgula (ex.: PSICOLOGO,NUTRICIONISTA)",
                null=True,
                verbose_name="Profissionais para consulta",
            ),
        ),
    ]
