# Generated by Django 5.2.6 on 2025-10-31 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_patientuser_alcohol_consumption_and_more"),
        ("alerts", "0002_alter_alert_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="professional",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.professionaluser",
            ),
            preserve_default=False,
        ),
    ]
