# Generated by Django 5.2.6 on 2025-11-08 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_patientuser_alcohol_consumption_and_more"),
        ("alerts", "0003_alert_professional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="professional",
        ),
        migrations.AddField(
            model_name="alert",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.patientuser",
            ),
        ),
    ]
