# Generated by Django 5.2.6 on 2025-11-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0004_remove_alert_professional_alert_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("safe", "Seguro"),
                    ("moderate", "Moderado"),
                    ("critical", "Crítico"),
                ],
                default="moderate",
                max_length=20,
            ),
        ),
    ]
