# Generated by Django 5.2.6 on 2025-10-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
