# Generated by Django 5.2.6 on 2025-10-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0002_alter_medication_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
