# Generated by Django 5.2.6 on 2025-10-28 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0003_alter_medication_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medication",
            options={"verbose_name": "Medicação", "verbose_name_plural": "Medicações"},
        ),
    ]
