# Generated by Django 5.2.6 on 2025-10-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manageruser",
            options={"verbose_name": "Gestor", "verbose_name_plural": "Gestores"},
        ),
        migrations.AlterModelOptions(
            name="patientuser",
            options={"verbose_name": "Paciente", "verbose_name_plural": "Pacientes"},
        ),
        migrations.AlterModelOptions(
            name="professionaluser",
            options={
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
            },
        ),
        migrations.AddField(
            model_name="patientuser",
            name="alcohol_consumption",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAO_BEBE", "Não bebe"),
                    ("SOCIALMENTE", "Socialmente"),
                    ("FREQUENTEMENTE", "Frequentemente"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="feed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SAUDAVEL", "Saudável"),
                    ("PARCIALMENTE", "Parcialmente Saudável"),
                    ("POUCO", "Pouco Saudável"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="last_consultation_interval_DCNT",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAO_CONSTA", "N/A"),
                    ("7_DIAS", "7 dias"),
                    ("15_DIAS", "15 dias"),
                    ("30_DIAS", "30 dias"),
                    ("60_DIAS", "60 dias"),
                    ("90_DIAS", "90 dias"),
                    ("6_MESES", "6 meses"),
                    ("1_ANO", "1 ano"),
                    ("MAIS_DE_1_ANO", "> 1 ano"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="salt_consumption",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADEQUADO", "Adequado"),
                    ("EXAGERADO", "Exagerado"),
                    ("NAO_SABE", "Não sabe"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="smoking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NUNCA_FUMOU", "Nunca fumou"),
                    ("EX_FUMANTE", "Ex-fumante"),
                    ("FUMANTE_ATUAL", "Fumante atual"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
