# Generated by Django 5.2.6 on 2025-10-28 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_alter_manageruser_options_alter_patientuser_options_and_more",
        ),
        ("locations", "0002_alter_address_options_alter_institution_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientuser",
            old_name="last_consultation_interval_DCNT",
            new_name="last_consultation",
        ),
        migrations.AddField(
            model_name="patientuser",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Idade"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="any_psychological_psychiatric_diagnosis",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Possui algum diagnóstico psicológico/psiquiátrico?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="any_psychological_psychiatric_diagnosis_answer",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Qual diagnóstico?"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="bolsa_familia",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Bolsa Família"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOLTEIRO", "Solteiro(a)"),
                    ("CASADO", "Casado(a)"),
                    ("UNIAO_ESTAVEL", "União estável"),
                    ("VIUVO", "Viúvo(a)"),
                    ("SEPARADO", "Separado(a) / Divorciado(a)"),
                ],
                max_length=40,
                null=True,
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CPF"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="delayed_wound_healing_after_scratches_or_bites",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Apresenta cicatrização demorada após arranhões ou mordidas?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="diagnosed_transmissible_disease_in_household",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHAGAS", "Doença de Chagas"),
                    ("LEISHMANIOSE", "Leishmaniose"),
                    ("TUBERCULOSE", "Tuberculose"),
                    ("TOXOPLASMOSE", "Toxoplasmose"),
                    ("ESPOROTRICOSE", "Esporotricose"),
                    ("HANSENIASE", "Hanseníase"),
                ],
                max_length=255,
                null=True,
                verbose_name="Você ou alguém em sua casa já foi diagnosticado com alguma doença transmissível?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="direct_contact_with_animal_bodily_fluids",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tem contato direto com fluidos corporais de animais?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="economic_factors_interfere_with_your_treatment",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Fatores econômicos interferem no tratamento?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="everyday_stress_interfere_with_your_BP_BS_control",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="O estresse do dia a dia interfere no controle da Pressão/Glicemia?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="family_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="Renda Familiar",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="family_responsability",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Resp. familiar"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="feel_receive_support_from_family_friends_to_maintain_treatment",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Sente que recebe apoio da família/amigos para manter o tratamento?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="gender",
            field=models.CharField(blank=True, null=True, verbose_name="Gênero"),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="has_difficulty_walking_or_activity",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Apresenta dificuldade para andar ou realizar atividades físicas?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="has_dyspnea",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Apresenta dispneia (falta de ar)?"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="has_edema",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Apresenta edema (inchaço)?"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="has_paresthesia_or_cramps",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Apresenta parestesia ou câimbras?"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="micro_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.microarea",
                verbose_name="Micro Área",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Ocupação"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="people_per_household",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="N⁰ de pessoas no domicílio"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="performs_physical_activity",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Realiza atividade física?"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="performs_physical_activity_answer",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Qual tipo de atividade física?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="presence_of_pets_at_home",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Possui animais de estimação em casa?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="presence_of_pets_at_home_answer",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Quais animais de estimação?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="race_ethnicity",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Raça/Etnia"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="received_guidance_on_zoonoses",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Já recebeu orientação sobre zoonoses?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="regularly_follow_health_guidelines",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Segue regularmente as orientações de saúde?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="requires_multidisciplinary_referral",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Necessita de encaminhamento multiprofissional?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="requires_multidisciplinary_referral_choose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PSICOLOGO", "Psicólogo"),
                    ("MEDICO_VETERINARIO", "Médico Veterinário"),
                    ("FISIOTERAPEUTA", "Fisioterapeuta"),
                    ("ASSISTENTE_SOCIAL", "Assistente Social"),
                    ("ENFERMEIRA", "Enfermeira"),
                    ("NUTRICIONISTA", "Nutricionista"),
                    ("CIRURGIA_DENTISTA", "Cirurgiã-Dentista"),
                ],
                max_length=255,
                null=True,
                verbose_name="Encaminhar para qual profissional?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="scholarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FUND_INCOMPL", "Fundamental Incompleto"),
                    ("FUND_COMPL", "Fundamental Completo"),
                    ("MED_INCOMPL", "Médio Incompleto"),
                    ("MED_COMPL", "Médio Completo"),
                    ("SUP_INCOMPL", "Superior Incompleto"),
                    ("SUP_COMPL", "Superior Completo"),
                    ("ANALFABETO", "Sem escolaridade / Analfabeto"),
                ],
                max_length=40,
                null=True,
                verbose_name="Escolaridade",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="use_psychotropic_medication",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Usa medicação psicotrópica?"
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="use_psychotropic_medication_answer",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Qual medicação psicotrópica?",
            ),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="whatsapp",
            field=models.BooleanField(blank=True, null=True, verbose_name="Whatsapp"),
        ),
        migrations.AddField(
            model_name="patientuser",
            name="your_animals_are_vaccinated",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Os animais são vacinados?"
            ),
        ),
    ]
