# Generated by Django 5.2.6 on 2025-10-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_rename_last_consultation_interval_dcnt_patientuser_last_consultation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientuser",
            name="alcohol_consumption",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAO_BEBE", "Não bebe"),
                    ("SOCIALMENTE", "Socialmente"),
                    ("FREQUENTEMENTE", "Frequentemente"),
                ],
                max_length=20,
                null=True,
                verbose_name="Consumo de Álcool",
            ),
        ),
        migrations.AlterField(
            model_name="patientuser",
            name="family_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Renda Familiar",
            ),
        ),
        migrations.AlterField(
            model_name="patientuser",
            name="feed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SAUDAVEL", "Saudável"),
                    ("PARCIALMENTE", "Parcialmente Saudável"),
                    ("POUCO", "Pouco Saudável"),
                ],
                max_length=20,
                null=True,
                verbose_name="Alimentação",
            ),
        ),
        migrations.AlterField(
            model_name="patientuser",
            name="gender",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Gênero"
            ),
        ),
        migrations.AlterField(
            model_name="patientuser",
            name="last_consultation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAO_CONSTA", "N/A"),
                    ("7_DIAS", "7 dias"),
                    ("15_DIAS", "15 dias"),
                    ("30_DIAS", "30 dias"),
                    ("60_DIAS", "60 dias"),
                    ("90_DIAS", "90 dias"),
                    ("6_MESES", "6 meses"),
                    ("1_ANO", "1 ano"),
                    ("MAIS_DE_1_ANO", "> 1 ano"),
                ],
                max_length=20,
                null=True,
                verbose_name="Última vez que foi a uma consulta para avaliar seu quadro?",
            ),
        ),
        migrations.AlterField(
            model_name="patientuser",
            name="salt_consumption",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADEQUADO", "Adequado"),
                    ("EXAGERADO", "Exagerado"),
                    ("NAO_SABE", "Não sabe"),
                ],
                max_length=20,
                null=True,
                verbose_name="Consumo de Sal",
            ),
        ),
        migrations.AlterField(
            model_name="patientuser",
            name="smoking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NUNCA_FUMOU", "Nunca fumou"),
                    ("EX_FUMANTE", "Ex-fumante"),
                    ("FUMANTE_ATUAL", "Fumante atual"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tabagismo",
            ),
        ),
    ]
