# Generated by Django 5.2.6 on 2025-11-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionaluser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Odontologista", "Odontologista"),
                    ("Enfermeiro", "Enfermeiro"),
                    ("ACS", "ACS"),
                    ("Psicólogo", "Psicólogo"),
                    ("Médico Veterinário", "Médico Veterinário"),
                    ("Fisioterapeuta", "Fisioterapeuta"),
                    ("Assistente Social", "Assistente Social"),
                    ("Nutricionista", "Nutricionista"),
                ],
                max_length=100,
            ),
        ),
    ]
