# Generated by Django 5.2.6 on 2026-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_professionaluser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientuser",
            name="diagnosed_transmissible_disease_in_household",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHAGAS", "Doença de Chagas"),
                    ("LEISHMANIOSE", "Leishmaniose"),
                    ("TUBERCULOSE", "Tuberculose"),
                    ("TOXOPLASMOSE", "Toxoplasmose"),
                    ("ESPOROTRICOSE", "Esporotricose"),
                    ("HANSENIASE", "Hanseníase"),
                    ("NAO", "Não"),
                ],
                max_length=255,
                null=True,
                verbose_name="Você ou alguém em sua casa já foi diagnosticado com alguma doença transmissível?",
            ),
        ),
    ]
