# Generated by Django 5.2.6 on 2025-10-30 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criação"),
                            ("UPDATE", "Atualização"),
                            ("DELETE", "Exclusão"),
                            ("RESTORE", "Restauração"),
                            ("VIEW", "Visualização"),
                            ("EXPORT", "Exportação"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("ACCESS_DENIED", "Acesso Negado"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Tipo de Objeto"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID do Objeto",
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Representação do Objeto",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, null=True, verbose_name="Mudanças"),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Valores Anteriores"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Novos Valores"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Chave da Sessão",
                    ),
                ),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Baixa"),
                            ("MEDIUM", "Média"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Nível de Sensibilidade",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados Adicionais"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="commons_aud_user_id_5060e3_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="commons_aud_action_018dbe_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="commons_aud_content_98d0c4_idx",
                    ),
                    models.Index(
                        fields=["sensitivity_level"],
                        name="commons_aud_sensiti_0d3ce3_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="commons_aud_ip_addr_33cc68_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("DATA_PROCESSING", "Processamento de Dados"),
                            ("DATA_SHARING", "Compartilhamento de Dados"),
                            ("MARKETING", "Marketing"),
                            ("RESEARCH", "Pesquisa"),
                            ("TREATMENT", "Tratamento Médico"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Consentimento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GRANTED", "Concedido"),
                            ("REVOKED", "Revogado"),
                            ("EXPIRED", "Expirado"),
                        ],
                        default="GRANTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Concessão"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Revogação"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Expiração"
                    ),
                ),
                ("purpose", models.TextField(verbose_name="Finalidade")),
                (
                    "data_categories",
                    models.JSONField(verbose_name="Categorias de Dados"),
                ),
                (
                    "legal_basis",
                    models.CharField(max_length=200, verbose_name="Base Legal"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "consent_text",
                    models.TextField(verbose_name="Texto do Consentimento"),
                ),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="consent_evidence/",
                        verbose_name="Arquivo de Evidência",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patientuser",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Consentimento",
                "verbose_name_plural": "Logs de Consentimento",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "consent_type"],
                        name="commons_con_patient_aa3cf9_idx",
                    ),
                    models.Index(
                        fields=["status"], name="commons_con_status_8a7d5a_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="commons_con_expires_e4f47d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "Visualização"),
                            ("DOWNLOAD", "Download"),
                            ("EXPORT", "Exportação"),
                            ("PRINT", "Impressão"),
                            ("SEARCH", "Busca"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Acesso",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "data_fields",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Campos Acessados"
                    ),
                ),
                ("purpose", models.TextField(verbose_name="Finalidade do Acesso")),
                (
                    "legal_basis",
                    models.CharField(max_length=200, verbose_name="Base Legal"),
                ),
                (
                    "retention_period",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Período de Retenção",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patientuser",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acesso a Dados",
                "verbose_name_plural": "Logs de Acesso a Dados",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["patient", "timestamp"],
                        name="commons_dat_patient_a64321_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="commons_dat_user_id_21ca49_idx",
                    ),
                    models.Index(
                        fields=["access_type"], name="commons_dat_access__cf20ef_idx"
                    ),
                ],
            },
        ),
    ]
