# Generated by Django 5.2.6 on 2025-09-20 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DCNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_diagnosed', models.BooleanField(blank=True, null=True)),
                ('uses_medication', models.BooleanField(blank=True, null=True)),
                ('medications_name', models.TextField(blank=True, null=True)),
                ('family_history', models.BooleanField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patientuser')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DM',
            fields=[
                ('dcnt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conditions.dcnt')),
                ('treatment_type', models.CharField(blank=True, choices=[('Oral', 'Oral'), ('Insulina', 'Insulina')], max_length=30, null=True)),
                ('treatment_type_other', models.TextField(blank=True, null=True)),
                ('diabetes_comorbidities', models.CharField(blank=True, choices=[('Cardiaca', 'Cardiaca'), ('Renal', 'Renal')], max_length=30, null=True)),
                ('diabetes_comorbidities_others', models.TextField(blank=True, null=True)),
                ('diabetic_foot', models.BooleanField(blank=True, null=True)),
                ('diabetic_foot_member', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=('conditions.dcnt',),
        ),
        migrations.CreateModel(
            name='HAS',
            fields=[
                ('dcnt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conditions.dcnt')),
                ('any_complications_HBP', models.CharField(blank=True, choices=[('AVC', 'AVC'), ('Infarto', 'Infarto')], max_length=30, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=('conditions.dcnt',),
        ),
        migrations.CreateModel(
            name='OtherDCNT',
            fields=[
                ('dcnt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conditions.dcnt')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=('conditions.dcnt',),
        ),
    ]
