# Generated by Django 5.2.6 on 2025-10-28 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dm",
            options={"verbose_name": "DM", "verbose_name_plural": "DMs"},
        ),
        migrations.AlterModelOptions(
            name="has",
            options={"verbose_name": "HAS", "verbose_name_plural": "HASs"},
        ),
        migrations.AlterModelOptions(
            name="otherdcnt",
            options={
                "verbose_name": "Outra DCNT",
                "verbose_name_plural": "Outras DCNT",
            },
        ),
    ]
