# Generated by Django 5.2.6 on 2025-11-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="has",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Altura",
            ),
        ),
    ]
