# Generated by Django 5.2.6 on 2026-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0002_has_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="has",
            name="any_complications_HBP",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVC", "AVC"),
                    ("INFARTO", "Infarto"),
                    ("DOENCA_RENAL", "Doença renal"),
                    ("SEM_COMPLICACOES", "Sem complicações"),
                ],
                max_length=30,
                null=True,
                verbose_name="Complicações relacionadas à pressão alta",
            ),
        ),
    ]
