# Generated by Django 5.2.6 on 2025-10-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_patientuser_alcohol_consumption_and_more"),
        ("conditions", "0002_alter_dm_options_alter_has_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dm",
            name="IMC",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="IMC",
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="abdominal_circumference",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Circunferência Abdominal (cm)",
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="adopted_conduct",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "CONFIRMACAO_LABORATORIAL",
                        "Encaminhado para confirmação laboratorial",
                    ),
                    ("INICIO_TRATAMENTO", "Início de tratamento"),
                    (
                        "ORIENTACAO_NUTRICIONAL",
                        "Orientação nutricional/educação em saúde",
                    ),
                    ("ENCAMINHAMENTO_MEDICO", "Encaminhamento médico"),
                ],
                max_length=255,
                null=True,
                verbose_name="Conduta Adotada",
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="adopted_conduct_other",
            field=models.TextField(
                blank=True, null=True, verbose_name="Outra Conduta (Especificar)"
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="age_over_45",
            field=models.BooleanField(default=False, verbose_name="Idade ≥ 45 anos"),
        ),
        migrations.AddField(
            model_name="dm",
            name="capillary_blood_glucose_random",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Glicemia Capilar Aleatória (mg/dL)",
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="fasting_capillary_blood_glucose",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Glicemia Capilar em Jejum (mg/dL)",
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="glycated_hemoglobin",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Hemoglobina Glicada (%)",
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Altura (m)",
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="high_blood_pressure",
            field=models.BooleanField(
                default=False, verbose_name="Hipertensão Arterial"
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="high_cholesterol_or_triglycerides",
            field=models.BooleanField(
                default=False, verbose_name="Colesterol ou Triglicerídeos Elevados"
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="history_of_gestational_diabetes",
            field=models.BooleanField(
                default=False, verbose_name="Histórico de Diabetes Gestacional"
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="overweight_or_obesity_imc_25",
            field=models.BooleanField(
                default=False, verbose_name="Sobrepeso ou Obesidade (IMC ≥ 25)"
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="physical_inactivity",
            field=models.BooleanField(default=False, verbose_name="Inatividade Física"),
        ),
        migrations.AddField(
            model_name="dm",
            name="polycystic_ovary_syndrome",
            field=models.BooleanField(
                default=False, verbose_name="Síndrome do Ovário Policístico"
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="screening_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NORMAL", "Normal"),
                    ("GLICEMIA_ALTERADA", "Glicemia alterada"),
                    ("SUSPEITA_DIABETES", "Suspeita de diabetes"),
                    ("DIAGNOSTICO_CONFIRMADO", "Diagnóstico confirmado"),
                ],
                max_length=255,
                null=True,
                verbose_name="Resultado do Rastreamento",
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="BP_assessment1_1",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Pressão Arterial 1ª Avaliação (Sistólica)",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="BP_assessment1_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Pressão Arterial 1ª Avaliação (Diastólica)",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="BP_assessment2_1",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Pressão Arterial 2ª Avaliação (Sistólica)",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="BP_assessment2_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Pressão Arterial 2ª Avaliação (Diastólica)",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="BP_classifications",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NORMAL", "Normal"),
                    ("PRE_HIPERTENSO", "Pré-hipertenso"),
                    ("HIPERTENSO_E1", "Hipertenso Estágio 1"),
                    ("HIPERTENSO_E2", "Hipertenso Estágio 2"),
                    ("HIPERTENSO_E3", "Hipertenso Estágio 3"),
                ],
                max_length=100,
                null=True,
                verbose_name="Classificação da PA",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="HDL_cholesterol",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Colesterol HDL (mg/dL)"
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="HDL_data",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Coleta do HDL"
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="IMC",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="IMC",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="abdominal_circumference",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Circunferência Abdominal (cm)",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="cholesterol_data",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Coleta do Colesterol"
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="conduct_adopted",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACOMPANHAMENTO_APS", "Acompanhamento na APS"),
                    ("ENCAMINHAMENTO_MEDICO", "Encaminhamento médico"),
                    ("ACONSELHAMENTO_GRUPO", "Aconselhamento em grupo"),
                ],
                max_length=255,
                null=True,
                verbose_name="Conduta Adotada",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="framingham_score",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAIXO", "<10% Baixo"),
                    ("MODERADO", "10–20% Moderado"),
                    ("ALTO", ">20% Alto"),
                ],
                max_length=100,
                null=True,
                verbose_name="Escore de Framingham",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="total_cholesterol",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Colesterol Total (mg/dL)"
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="dcnt",
            name="family_history",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Histórico familiar"
            ),
        ),
        migrations.AlterField(
            model_name="dcnt",
            name="is_diagnosed",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Diagnóstico confirmado"
            ),
        ),
        migrations.AlterField(
            model_name="dcnt",
            name="medications_name",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nome dos medicamentos"
            ),
        ),
        migrations.AlterField(
            model_name="dcnt",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.patientuser",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="dcnt",
            name="uses_medication",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIM", "Sim"),
                    ("NAO", "Não"),
                    ("IRREGULAR", "Irregular"),
                    ("NAO_SE_APLICA", "Não se aplica"),
                ],
                max_length=25,
                null=True,
                verbose_name="Uso de medicação",
            ),
        ),
        migrations.AlterField(
            model_name="dm",
            name="diabetes_comorbidities",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARDIACA", "Cardíaca"),
                    ("RENAL", "Renal"),
                    ("VISUAL", "Visual"),
                    ("VASCULAR", "Vascular"),
                ],
                max_length=30,
                null=True,
                verbose_name="Comorbidades em decorrência da diabetes",
            ),
        ),
        migrations.AlterField(
            model_name="dm",
            name="diabetes_comorbidities_others",
            field=models.TextField(
                blank=True, null=True, verbose_name="Outras comorbidades"
            ),
        ),
        migrations.AlterField(
            model_name="dm",
            name="diabetic_foot",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Presença de pé diabético"
            ),
        ),
        migrations.AlterField(
            model_name="dm",
            name="diabetic_foot_member",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Membro afetado pelo pé diabético",
            ),
        ),
        migrations.AlterField(
            model_name="dm",
            name="treatment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MEDICAMENTOSO", "Medicamentoso (oral)"),
                    ("INSULINA", "Insulina"),
                    ("ALIMENTAR_ESTILO_VIDA", "Alimentar/estilo de vida"),
                ],
                max_length=30,
                null=True,
                verbose_name="Tipo de tratamento",
            ),
        ),
        migrations.AlterField(
            model_name="dm",
            name="treatment_type_other",
            field=models.TextField(
                blank=True, null=True, verbose_name="Outro tipo de tratamento"
            ),
        ),
        migrations.AlterField(
            model_name="has",
            name="any_complications_HBP",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVC", "AVC"),
                    ("INFARTO", "Infarto"),
                    ("DOENCA_RENAL", "Doença renal"),
                ],
                max_length=30,
                null=True,
                verbose_name="Complicações relacionadas à pressão alta",
            ),
        ),
        migrations.AlterField(
            model_name="otherdcnt",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome da DCNT"
            ),
        ),
    ]
