# Generated by Django 5.2.6 on 2025-10-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_patientuser_alcohol_consumption_and_more"),
        (
            "conditions",
            "0003_dm_imc_dm_abdominal_circumference_dm_adopted_conduct_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dcnt",
            name="patient",
        ),
        migrations.AddField(
            model_name="dm",
            name="patient",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.patientuser",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="patient",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.patientuser",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddField(
            model_name="otherdcnt",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.patientuser",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddConstraint(
            model_name="otherdcnt",
            constraint=models.UniqueConstraint(
                fields=("patient", "name"), name="unique_patient_other_dcnt"
            ),
        ),
    ]
