# Generated by Django 5.2.6 on 2026-05-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0003_alter_has_any_complications_hbp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dm",
            name="glycated_hemoglobin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Hemoglobina Glicada (%)",
            ),
        ),
    ]
