# Generated by Django 5.2.6 on 2025-10-28 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Endereço", "verbose_name_plural": "Endereços"},
        ),
        migrations.AlterModelOptions(
            name="institution",
            options={
                "verbose_name": "Instituição",
                "verbose_name_plural": "Instituições",
            },
        ),
        migrations.AlterModelOptions(
            name="microarea",
            options={
                "verbose_name": "Micro-Área",
                "verbose_name_plural": "Micro-Áreas",
            },
        ),
    ]
